import { Banknote, Car, Music, ShoppingCart, Zap } from "lucide-react-native";
import { Transaction } from "../types/transaction";

export const RECENT_ACTIVITY: Transaction[] = [
  {
    id: "txn_apple_music",
    title: "Apple Music",
    category: "entertainment",
    amount: -32.5,
    currency: "USD",
    date: "2026-08-24",
    icon: Music,
    iconColor: "#EC4899",
    iconBackground: "#FCE7F3",
  },
  {
    id: "txn_salary",
    title: "Monthly Salary",
    category: "income",
    amount: 5200.0,
    currency: "USD",
    date: "2026-08-23",
    icon: Banknote,
    iconColor: "#22C55E",
    iconBackground: "#DCFCE7",
  },
  {
    id: "txn_groceries",
    title: "Whole Foods",
    category: "groceries",
    amount: -84.32,
    currency: "USD",
    date: "2026-08-22",
    icon: ShoppingCart,
    iconColor: "#F59E0B",
    iconBackground: "#FEF3C7",
  },
  {
    id: "txn_uber",
    title: "Uber",
    category: "transport",
    amount: -15.8,
    currency: "USD",
    date: "2026-08-22",
    icon: Car,
    iconColor: "#4F6EF7",
    iconBackground: "#E8ECFE",
  },
  {
    id: "txn_electricity",
    title: "Electricity Bill",
    category: "utilities",
    amount: -120.0,
    currency: "USD",
    date: "2026-08-21",
    icon: Zap,
    iconColor: "#8B5CF6",
    iconBackground: "#EDE9FE",
  },
];
